class BuilderController < ApplicationController
  layout "builder"

  THEME_FILE = Rails.root.join("app/assets/stylesheets/brand.css")

  RADIUS_VALUES = {
    "none" => "0",
    "sm" => "0.25rem",
    "md" => "0.375rem",
    "lg" => "0.5rem",
    "xl" => "0.75rem",
    "full" => "9999px"
  }.freeze

  # Color variables editable in builder (mapped to hex color pickers)
  # Each entry becomes a color picker pair (light + dark)
  EDITABLE_VARS = %w[
    background foreground
    card card-foreground
    primary primary-foreground
    secondary secondary-foreground
    accent accent-foreground
    muted muted-foreground
    border input input-focus input-ring
    destructive success warning info
  ].freeze

  def index
    @theme = parse_theme_brand
  end

  def download
    theme = parse_theme_brand
    # Merge builder color params (param keys use underscores, CSS vars use dashes)
    EDITABLE_VARS.each do |var|
      param_key = var.tr("-", "_")
      if params[param_key].present?
        oklch = oklch_from_hex(params[param_key])
        alpha = params["#{param_key}_alpha"]
        oklch = oklch.sub(")", " / #{alpha}%)") if alpha.present? && alpha.to_s != "100"
        theme[:light][var] = oklch
      end
      dark_key = "#{param_key}_dark"
      if params[dark_key].present?
        oklch = oklch_from_hex(params[dark_key])
        alpha = params["#{dark_key}_alpha"]
        oklch = oklch.sub(")", " / #{alpha}%)") if alpha.present? && alpha.to_s != "100"
        theme[:dark][var] = oklch
      end
    end

    # Merge builder radius params
    if params[:radius_base].present?
      theme[:light]["radius-base"] = RADIUS_VALUES[params[:radius_base]] || theme[:light]["radius-base"]
    end
    if params[:radius_btn].present?
      theme[:light]["radius-btn"] = RADIUS_VALUES[params[:radius_btn]] || theme[:light]["radius-btn"]
    end
    if params[:radius_form].present?
      theme[:light]["radius-field"] = RADIUS_VALUES[params[:radius_form]] || theme[:light]["radius-field"]
    end

    send_data generate_theme_css(theme),
              filename: "brand.css",
              type: "text/css",
              disposition: "attachment"
  end

  private

  def parse_theme_brand
    css = File.read(THEME_FILE)
    light = {}
    dark = {}

    # Extract :root block
    if (root_match = css.match(/:root\s*\{([^}]+)\}/m))
      root_match[1].scan(/--([\w-]+):\s*(.+?);/).each do |name, value|
        light[name] = value.strip
      end
    end

    # Extract .dark block
    if (dark_match = css.match(/\.dark\s*\{([^}]+)\}/m))
      dark_match[1].scan(/--([\w-]+):\s*(.+?);/).each do |name, value|
        dark[name] = value.strip
      end
    end

    # Convert editable vars to hex for color pickers, extract alpha where present
    hex = {}
    alpha = {}
    EDITABLE_VARS.each do |var|
      light_val = resolve_color_value(light, var)
      dark_val = resolve_color_value(dark, var) || resolve_color_value(light, var)
      if light_val
        hex[var] = oklch_to_hex(light_val[:oklch])
        alpha[var] = light_val[:alpha] if light_val[:alpha]
      end
      if dark_val
        hex["#{var}_dark"] = oklch_to_hex(dark_val[:oklch])
        alpha["#{var}_dark"] = dark_val[:alpha] if dark_val[:alpha]
      end
    end

    # Fallback: input-focus and input-ring derive from primary when not directly set
    %w[input-focus input-ring].each do |var|
      key = var.tr("-", "_")
      hex[key] ||= hex["primary"]
      hex["#{key}_dark"] ||= hex["primary_dark"]
    end
    # Default alpha for input-focus/input-ring from brand.css
    alpha["input_focus"] ||= 40
    alpha["input_focus_dark"] ||= 40
    alpha["input_ring"] ||= 10
    alpha["input_ring_dark"] ||= 10

    # Resolve radius defaults from brand.css values
    radius_base = resolve_radius_name(light["radius-base"]) || "md"
    radius_btn = resolve_radius_name(light["radius-btn"])
    radius_field = resolve_radius_name(light["radius-field"]) || "md"

    { light: light, dark: dark, hex: hex, alpha: alpha, radius_base: radius_base, radius_btn: radius_btn, radius_form: radius_field }
  end

  def generate_theme_css(theme)
    lines_root = theme[:light].map { |k, v| "  --#{k}: #{v};" }.join("\n")
    lines_dark = theme[:dark].map { |k, v| "  --#{k}: #{v};" }.join("\n")

    <<~CSS
      /*
       * Semantic Color Theme
       * Generated by Theme Builder
       */

      :root {
      #{lines_root}
      }

      .dark {
      #{lines_dark}
      }
    CSS
  end

  # Returns { oklch: "oklch(L C H)", alpha: N } or nil
  def resolve_color_value(vars, name)
    value = vars[name]
    return nil unless value
    # Resolve "var(--foreground)" to the actual value
    if (m = value.match(/\Avar\(--(.+?)\)\z/))
      value = vars[m[1]]
      return nil unless value
    end
    # Skip relative color syntax — oklch(from ...)
    return nil if value.include?("from var(") || value.include?("from ")
    return nil unless value.start_with?("oklch(")
    # Extract alpha if present: "oklch(1 0 0 / 10%)" → oklch + alpha
    if (alpha_match = value.match(%r{\s*/\s*([\d.]+)%?\s*\)}))
      alpha = alpha_match[1].to_f
      oklch = value.sub(%r{\s*/\s*[\d.]+%?\s*\)}, ")")
      { oklch: oklch, alpha: alpha.round }
    else
      { oklch: value }
    end
  end

  def resolve_radius_name(value)
    return nil unless value
    # Match "theme(--radius-md)" format
    if (m = value.match(/theme\(--radius-(\w+)\)/))
      return m[1]
    end
    # Match "var(--radius-base)" — inherits from base, return nil
    return nil if value.match?(/var\(--radius/)
    # Match raw value like "0.375rem"
    RADIUS_VALUES.key(value) || "md"
  end

  def oklch_from_hex(hex)
    lch = hex_to_oklch(hex)
    format_oklch(lch)
  end

  def format_oklch(oklch)
    if oklch[:c] < 0.001
      "oklch(#{format("%.3f", oklch[:l])} 0 0)"
    else
      "oklch(#{format("%.3f", oklch[:l])} #{format("%.3f", oklch[:c])} #{oklch[:h].round(1)})"
    end
  end

  def hex_to_oklch(hex)
    hex = hex.delete("#")
    r, g, b = hex.scan(/../).map { |c| c.to_i(16) / 255.0 }

    lr, lg, lb = [r, g, b].map { |c| c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055)**2.4 }

    l_ = (0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb)**(1.0 / 3)
    m_ = (0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb)**(1.0 / 3)
    s_ = (0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb)**(1.0 / 3)

    l = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_
    a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_
    b_val = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_

    c = Math.sqrt(a**2 + b_val**2)
    h = Math.atan2(b_val, a) * 180 / Math::PI
    h += 360 if h < 0

    { l: l, c: c, h: h }
  end

  def oklch_to_hex(oklch_str)
    # Parse "oklch(0.55 0.245 264)" or "oklch(1 0 0)"
    match = oklch_str.match(/oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)/)
    return "#000000" unless match

    l, c, h = match[1].to_f, match[2].to_f, match[3].to_f

    h_rad = h * Math::PI / 180
    a = c * Math.cos(h_rad)
    b = c * Math.sin(h_rad)

    # Oklab to linear RGB
    l_ = (l + 0.3963377774 * a + 0.2158037573 * b)**3
    m_ = (l - 0.1055613458 * a - 0.0638541728 * b)**3
    s_ = (l - 0.0894841775 * a - 1.2914855480 * b)**3

    lr = 4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_
    lg = -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_
    lb = -0.0041960863 * l_ - 0.7034186147 * m_ + 1.7076147010 * s_

    # Linear to sRGB
    rgb = [lr, lg, lb].map do |v|
      v = v.clamp(0, 1)
      v <= 0.0031308 ? v * 12.92 : 1.055 * (v**(1.0 / 2.4)) - 0.055
    end

    "#" + rgb.map { |v| (v.clamp(0, 1) * 255).round.to_s(16).rjust(2, "0") }.join
  end
end
