class BuilderController < ApplicationController
  layout "builder"

  DEFAULTS = {
    primary: "#6d28d9",
    primary_dark: "#8b5cf6",
    secondary: "#f0eef5",
    secondary_dark: "#2a2640",
    background: "#f9f9fb",
    background_dark: "#1a1625",
    radius_base: "lg",
    radius_form: "md"
  }.freeze

  RADIUS_VALUES = {
    "none" => "0",
    "sm" => "0.25rem",
    "md" => "0.375rem",
    "lg" => "0.5rem",
    "xl" => "0.75rem",
    "full" => "9999px"
  }.freeze

  def index
    @theme = DEFAULTS
  end

  def download
    theme = DEFAULTS.merge(theme_params.to_h.symbolize_keys)
    css_content = generate_theme_css(theme)

    send_data css_content,
              filename: "theme.css",
              type: "text/css",
              disposition: "attachment"
  end

  private

  def theme_params
    params.permit(:primary, :primary_dark, :secondary, :secondary_dark,
                  :background, :background_dark, :radius_base, :radius_form)
  end

  def generate_theme_css(theme)
    radius_base = RADIUS_VALUES[theme[:radius_base]] || RADIUS_VALUES["lg"]
    radius_form = RADIUS_VALUES[theme[:radius_form]] || RADIUS_VALUES["md"]

    primary = hex_to_oklch(theme[:primary])
    secondary = hex_to_oklch(theme[:secondary])
    background = hex_to_oklch(theme[:background])

    primary_dark = hex_to_oklch(theme[:primary_dark].presence || theme[:primary])
    secondary_dark = hex_to_oklch(theme[:secondary_dark].presence || theme[:secondary])
    background_dark = hex_to_oklch(theme[:background_dark].presence || theme[:background])

    <<~CSS
      /*
       * Theme Variables
       * Generated by Theme Builder
       */

      :root {
        /* Primary */
        --primary: #{format_oklch(primary)};
        --primary-hover: oklch(from var(--primary) calc(l - 0.06) c h);
        --primary-active: oklch(from var(--primary) calc(l - 0.12) c h);
        --primary-foreground: oklch(1 0 0);

        /* Secondary */
        --secondary: #{format_oklch(secondary)};
        --secondary-hover: oklch(from var(--secondary) calc(l - 0.03) c h);

        /* Background */
        --background: #{format_oklch(background)};

        /* Radius */
        --radius-base: #{radius_base};
        --radius-field: #{radius_form};
      }

      /*
       * Dark Theme
       * Apply .dark class to html element to enable
       */
      .dark {
        /* Primary */
        --primary: #{format_oklch(primary_dark)};
        --primary-foreground: oklch(1 0 0);

        /* Secondary */
        --secondary: #{format_oklch(secondary_dark)};

        /* Background */
        --background: #{format_oklch(background_dark)};
      }
    CSS
  end

  def format_oklch(oklch)
    if oklch[:c] < 0.001
      "oklch(#{format("%.3f", oklch[:l])} 0 0)"
    else
      "oklch(#{format("%.3f", oklch[:l])} #{format("%.3f", oklch[:c])} #{oklch[:h].round(1)})"
    end
  end

  def hex_to_oklch(hex)
    hex = hex.delete("#")
    r, g, b = hex.scan(/../).map { |c| c.to_i(16) / 255.0 }

    lr, lg, lb = [r, g, b].map { |c| c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055)**2.4 }

    l_ = (0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb)**(1.0 / 3)
    m_ = (0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb)**(1.0 / 3)
    s_ = (0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb)**(1.0 / 3)

    l = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_
    a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_
    b_val = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_

    c = Math.sqrt(a**2 + b_val**2)
    h = Math.atan2(b_val, a) * 180 / Math::PI
    h += 360 if h < 0

    { l: l, c: c, h: h }
  end
end
