class BuilderController < ApplicationController
  layout "builder"
  DEFAULTS = {
    accent_hue: 262,
    gray_chroma: 0.006,
    radius_base: "lg",
    radius_form: "md"
  }.freeze

  RADIUS_VALUES = {
    "none" => "0",
    "sm" => "0.25rem",
    "md" => "0.375rem",
    "lg" => "0.5rem",
    "xl" => "0.75rem",
    "full" => "9999px"
  }.freeze

  def index
    @theme = DEFAULTS
  end

  def download
    theme = DEFAULTS.merge(theme_params.to_h.symbolize_keys)
    css_content = generate_theme_css(theme)

    send_data css_content,
              filename: "theme.css",
              type: "text/css",
              disposition: "attachment"
  end

  private

  def theme_params
    params.permit(:accent_hue, :gray_chroma, :radius_base, :radius_form, :theme)
  end

  def generate_theme_css(theme)
    radius_base = RADIUS_VALUES[theme[:radius_base]] || RADIUS_VALUES["lg"]
    radius_form = RADIUS_VALUES[theme[:radius_form]] || RADIUS_VALUES["md"]
    include_dark = theme[:theme] == "dark"

    css = <<~CSS
      /*
       * Theme Variables
       * Generated by Theme Builder
       */

      :root {
        --accent-hue: #{theme[:accent_hue]};
        --gray-chroma: #{theme[:gray_chroma]};
        --radius-base: #{radius_base};
        --radius-field: #{radius_form};
      }
    CSS

    css += dark_theme_css(theme) if include_dark
    css
  end

  def dark_theme_css(_theme)
    <<~CSS

      /*
       * Dark Theme
       * Apply .dark class to html element to enable
       */
      .dark {
        --color-background: oklch(0.13 0.004 var(--accent-hue));
        --color-foreground: oklch(0.98 0 0);
        --color-surface: oklch(0.17 0.006 var(--accent-hue));
        --color-surface-foreground: oklch(0.98 0 0);
        --color-overlay: oklch(0 0 0 / 0.7);

        --color-accent: oklch(calc(var(--accent-lightness) + 0.05) var(--accent-chroma) var(--accent-hue));
        --color-accent-hover: oklch(calc(var(--accent-lightness) + 0.1) var(--accent-chroma) var(--accent-hue));
        --color-accent-active: oklch(var(--accent-lightness) var(--accent-chroma) var(--accent-hue));
        --color-accent-foreground: oklch(1 0 0);

        --color-muted: oklch(0.2 0.005 var(--accent-hue));
        --color-muted-hover: oklch(0.24 0.008 var(--accent-hue));
        --color-muted-foreground: oklch(0.6 0.01 var(--accent-hue));

        --color-border: oklch(0.28 0.008 var(--accent-hue));
        --color-input: oklch(0.32 0.008 var(--accent-hue));
        --color-input-focus: oklch(0.55 0.15 var(--accent-hue));
        --color-ring: oklch(0.5 0.12 var(--accent-hue) / 0.35);

        --color-destructive: oklch(0.65 0.22 25);
        --color-destructive-hover: oklch(0.7 0.24 25);
        --color-destructive-foreground: oklch(1 0 0);
        --color-destructive-soft: oklch(0.2 0.04 25);
        --color-destructive-soft-hover: oklch(0.24 0.05 25);
        --color-destructive-soft-foreground: oklch(0.8 0.18 25);
        --color-destructive-border: oklch(0.35 0.08 25);

        --color-success: oklch(0.7 0.19 145);
        --color-success-hover: oklch(0.75 0.2 145);
        --color-success-foreground: oklch(0.15 0.04 145);
        --color-success-soft: oklch(0.2 0.035 145);
        --color-success-soft-hover: oklch(0.24 0.045 145);
        --color-success-soft-foreground: oklch(0.8 0.16 145);
        --color-success-border: oklch(0.35 0.07 145);

        --color-warning: oklch(0.8 0.16 85);
        --color-warning-hover: oklch(0.85 0.17 85);
        --color-warning-foreground: oklch(0.2 0.04 85);
        --color-warning-soft: oklch(0.22 0.035 85);
        --color-warning-soft-hover: oklch(0.26 0.045 85);
        --color-warning-soft-foreground: oklch(0.85 0.14 85);
        --color-warning-border: oklch(0.38 0.07 85);

        --color-info: oklch(0.7 0.16 240);
        --color-info-hover: oklch(0.75 0.18 240);
        --color-info-foreground: oklch(1 0 0);
        --color-info-soft: oklch(0.2 0.04 240);
        --color-info-soft-hover: oklch(0.24 0.05 240);
        --color-info-soft-foreground: oklch(0.8 0.14 240);
        --color-info-border: oklch(0.35 0.08 240);

        --color-link: oklch(calc(var(--accent-lightness) + 0.1) var(--accent-chroma) var(--accent-hue));
        --color-link-hover: oklch(calc(var(--accent-lightness) + 0.15) var(--accent-chroma) var(--accent-hue));

        --color-tooltip: oklch(0.92 0.01 var(--accent-hue));
        --color-tooltip-foreground: oklch(0.15 0.01 var(--accent-hue));
      }
    CSS
  end
end
